<?php
/* @var $this PaymentController */
/* @var $data Payment */
?>

<div class="view">

	<?php
require_once(Yii::app()->basePath . '/views/payment/OAuth.php');

//pesapal params
$token = $params = NULL;


$consumer_key = 'onpM4VFAaAG2sSo0rmsOTydM9p85Dgm7';
$consumer_secret = 'OnlQymY1+sKPliIJHPCAa+eE+/o=';
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

//get form details
$amount = '1200'; //$_POST['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = 'no description'; //$_POST['description'];
$type = 'MERCHANT'; //$_POST['type']; //default value = MERCHANT
$reference ='1'; // $_POST['reference'];//unique order id of the transaction, generated by merchant
$first_name = 'gilbert'; //$_POST['first_name'];
$last_name = 'kabui'; //$_POST['last_name'];
$email = 'gilbertkarogo@gmail.com'; //$_POST['email'];
$phonenumber = '0724848463'; //ONE of email or phonenumber is required

$callback_url = 'http://www.cloudsafari.com/redirect.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe>


</div>